version: '3.1'
services:

    database:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        volumes:
           - ./storage/mysql:/var/lib/mysql
        ports:
          - 3007:3006
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - database
        ports:
            - 6388:80
        environment:
            - PMA_HOST=database
            - UPLOAD_LIMIT=300M
    web:
      build:
        context: ./
        dockerfile: ./dockers/web.Dockerfile
      ports:
        - 8098:80
      volumes:
         - ./:/var/www
         - /var/www/vendor
      links:
        - app
    app:
      build:
        context: ./
        dockerfile: ./dockers/app.Dockerfile
      volumes:
        - ./:/var/www
        - ./bootstrap/cache:/var/www/bootstrap/cache
        - ./storage/framework:/var/www/storage/framework
        - /var/www/vendor
      environment:
        - "DB_PORT=3306"
        - "DB_HOST=database"
        - "TZ=Asia/Bangkok"
      links:
        - database
